#!/usr/bin/env bash
# Bump the pinned Rust toolchain to the latest stable release and re-pin the build
# inputs.
#
# Rewrites the channel in rust-toolchain.toml, the base image (tag + digest) in the
# devcontainer Dockerfile, and the apk build-dep versions in apk-pins.txt, keeping the
# pin reproducible. Review the diff, then run ./build.sh. Idempotent: a no-op when
# already current. Requires docker (resolves the image digest + apk versions).
set -euo pipefail
cd "$(dirname "$0")"

# Ask the local rustup for the latest stable version rather than scraping
# release pages.
rustup update stable
LATEST=$(rustup run stable rustc --version | awk '{print $2}')
echo "latest stable: $LATEST"

sed -i -E "s/^channel = \".*\"/channel = \"$LATEST\"/" rust-toolchain.toml

# Resolve the matching Rust Alpine image digest so the FROM line stays pinned, not
# just tagged. ALPINE_TAG fixes the Alpine minor; bump it deliberately (a new Alpine
# minor can change the libseccomp/libcap-ng versions linked into the binary).
ALPINE_TAG="${ALPINE_TAG:-alpine3.21}"
IMG="rust:${LATEST}-${ALPINE_TAG}"
docker pull -q "$IMG" >/dev/null
DIGEST=$(docker inspect --format '{{index .RepoDigests 0}}' "$IMG" | sed -E 's/.*@//')
sed -i -E "s#^FROM rust:[^ ]*#FROM ${IMG}@${DIGEST}#" .devcontainer/Dockerfile

# Re-pin the apk packages to the versions the (digest-pinned) base image resolves —
# Alpine has no snapshot service, so the image digest freezes the toolchain but
# `apk add` would otherwise float the package versions. Done for both pin files: the
# build image's deps (.devcontainer/apk-pins.txt) and the kernel build's extra deps
# (kernel/apk-pins.txt) — both resolve from the same Alpine repos as $IMG.
pin_apk() {
    local pins=$1 header=$2 names resolved
    # space-separated (single line) so it injects cleanly into the `sh -c` script below
    names=$(grep -vE '^[[:space:]]*(#|$)' "$pins" | sed 's/=.*//' | tr '\n' ' ')
    echo "resolving apk versions for $pins in $IMG ..."
    # Install the packages, then read each one's installed version from `apk list
    # --installed` (lines "<name>-<version> <arch> …"): grep the package's line
    # (anchored, version starts with a digit so libcap-ng vs libcap-ng-dev don't
    # collide), take the first field, strip the "<name>-" prefix.
    resolved=$(docker run --rm "$IMG" sh -ec '
        apk add --no-cache -q '"$names"' >/dev/null 2>&1 || true
        for p in '"$names"'; do
            v=$(apk list --installed "$p" 2>/dev/null \
                | grep -E "^${p}-[0-9]" | head -1 | cut -d" " -f1 | sed "s/^${p}-//")
            printf "%s=%s\n" "$p" "$v"
        done')
    {
        printf '%s\n' "$header"
        local p v
        for p in $names; do
            v=$(printf '%s\n' "$resolved" | sed -nE "s/^${p}=(.+)$/\1/p" | head -1)
            case "$v" in
                [0-9]*) ;; # a version starts with a digit
                *)
                    echo >&2 "ERROR: resolved apk version for '$p' looks wrong: '${v}' (in $IMG)"
                    exit 1
                    ;;
            esac
            echo "$p=$v"
        done
    } >"$pins.new" && mv "$pins.new" "$pins"
}
pin_apk .devcontainer/apk-pins.txt \
    '# Build-dep apk packages for the virtkit build image, pinned to exact versions for
# byte-reproducible builds (Alpine has no snapshot service). Regenerated by ./update.sh
# against the pinned base image — do NOT edit by hand.'
pin_apk kernel/apk-pins.txt \
    '# Kernel-build apk packages (added on top of virtkit-build), pinned to exact
# versions for byte-reproducible builds. Regenerated by ./update.sh — do NOT edit by
# hand. (gcc/musl-dev/ca-certificates come from the base; coreutils & friends replace
# the busybox applets the kernel build trips over.)'

echo "updated:"
grep -E '^channel' rust-toolchain.toml
grep -E '^FROM'    .devcontainer/Dockerfile
for pins in .devcontainer/apk-pins.txt kernel/apk-pins.txt; do
    echo "apk pins ($pins):"
    grep -vE '^[[:space:]]*(#|$)' "$pins" | sed 's/^/  /'
done
